"""
AI Recommendations View for SalesPulse AI Streamlit Frontend.
Surfaces personalized, data-backed coaching recommendations per sales representative.
"""

import streamlit as st
from Frontend.utils.api import get_coaching_recommendations
from Frontend.utils.components import render_section_header

def render_recommendations_view():
    render_section_header("AI Coaching Recommendations", "Automated, evidence-based coaching advice generated by comparing rep metrics to top-performer benchmarks.")

    rep_name = st.selectbox(
        "Select Sales Representative to Review",
        ["Aditya Kulkarni", "David Miller", "Emma Watson", "Michael Chen", "Sarah Jenkins"],
        index=0
    )

    recs = get_coaching_recommendations(rep_name)

    st.markdown(f"""
        <div style='background: white; padding: 1.25rem; border: 1px solid #e2e8f0; border-radius: 16px; margin-top: 1rem; box-shadow: 0 4px 15px -3px rgba(15,23,42,0.03);'>
            <h3 style='font-size: 1.15rem; font-weight: 800; color: #0f172a; margin: 0 0 0.25rem 0; font-family: Outfit, sans-serif;'>Coaching Playbook for {rep_name}</h3>
            <p style='font-size: 0.83rem; color: #64748b; margin-bottom: 1rem;'>3 active recommendations identified from recent activity logs & email threads</p>
    """, unsafe_allow_html=True)

    for idx, rec in enumerate(recs, 1):
        with st.expander(f"💡 Recommendation {idx}: {rec['title']}", expanded=True):
            col_a, col_b = st.columns([2, 1])

            with col_a:
                st.markdown(f"**Metric Evaluated:** `{rec['metric']}`")
                st.markdown(f"**Current Metric Value:** <span style='color: #ef4444; font-weight: bold;'>{rec['current_value']}</span> (Benchmark Goal: <span style='color: #10b981; font-weight: bold;'>{rec['target_benchmark']}</span>)", unsafe_allow_html=True)
                st.markdown(f"**AI Behavioural Analysis:** {rec['recommendation']}")

            with col_b:
                st.markdown(f"**Estimated Revenue Impact:**")
                st.info(rec['impact'])

            st.markdown(f"**Actionable Playbook Step:**")
            st.success(f"✅ {rec['action']}")

    st.markdown("</div>", unsafe_allow_html=True)
