import { BrainCircuit, CheckCircle, Clock, TrendingUp } from 'lucide-react'
import Card from '@/components/ui/Card'
import Badge from '@/components/ui/Badge'
import StatCard from '@/components/cards/StatCard'
import { useAuth } from '@/contexts/AuthContext'

const ALL_TIPS = [
  {
    id: 1,
    rep: 'David Miller',
    repInitials: 'DM',
    severity: 'urgent',
    tone: 'slate',
    metric: 'Response Time',
    issue: 'Response time on 3 open deals exceeds the 4-hour benchmark.',
    action: 'Prioritize same-day replies on Stark Industries, Wayne Enterprises, and GlobalTech deals today.',
    impact: '+12% win-rate if resolved within 1 week (based on team data)',
    created: '2 hours ago',
  },
  {
    id: 2,
    rep: 'Emma Watson',
    repInitials: 'EW',
    severity: 'warning',
    tone: 'slate',
    metric: 'Follow-up Frequency',
    issue: 'Follow-up rate dropped 40% vs prior month — 2 deals showing no activity for 10+ days.',
    action: 'Schedule follow-up calls for Oscorp and LexCorp deals before end of week.',
    impact: 'Stalled deals at this stage convert at 28% — re-engagement improves this to 51%',
    created: '5 hours ago',
  },
  {
    id: 3,
    rep: 'Sarah Jenkins',
    repInitials: 'SJ',
    severity: 'opportunity',
    tone: 'green',
    metric: 'Win Pattern',
    issue: '3 of 4 enterprise proposals accepted in the last 30 days.',
    action: 'Apply the same slide deck structure and pricing approach to the pending Avengers Corp proposal.',
    impact: 'Replicating winning patterns boosts close probability by an estimated 18%',
    created: '1 day ago',
  },
  {
    id: 4,
    rep: 'Michael Chen',
    repInitials: 'MC',
    severity: 'info',
    tone: 'blue',
    metric: 'Tone Score',
    issue: 'Email tone score dipped from 80 → 64 in the last week.',
    action: 'Review the last 3 outbound emails and soften language in follow-ups — avoid pressure framing.',
    impact: 'Deals where tone score stays above 70 close 33% faster',
    created: '1 day ago',
  },
  {
    id: 5,
    rep: 'David Miller',
    repInitials: 'DM',
    severity: 'warning',
    tone: 'slate',
    metric: 'Deal Health',
    issue: 'Hardware Fleet deal at Wayne Enterprises has received a competitor proposal.',
    action: 'Request a discovery call within 48 hours to understand competitor\'s offer and counter with updated pricing.',
    impact: 'Deals with competitive threat handled within 72h retain at 64% vs 29% with no action',
    created: '2 days ago',
  },
]

const SEVERITY_STYLES = {
  urgent:      { label: 'Urgent',      border: 'border-l-red-500',   bg: 'bg-red-50',    text: 'text-red-700',    badge: 'slate' },
  warning:     { label: 'Warning',     border: 'border-l-amber-400', bg: 'bg-amber-50',  text: 'text-amber-700',  badge: 'slate' },
  opportunity: { label: 'Opportunity', border: 'border-l-emerald-500', bg: 'bg-emerald-50', text: 'text-emerald-700', badge: 'green' },
  info:        { label: 'Info',        border: 'border-l-blue-500',  bg: 'bg-blue-50',   text: 'text-blue-700',   badge: 'blue' },
}

export default function Recommendations() {
  const { user } = useAuth()
  const role = user?.role?.toLowerCase()

  // Reps only see their own tips
  const tips = role === 'representative'
    ? ALL_TIPS.filter((t) => t.rep === user?.name)
    : ALL_TIPS

  const urgent = tips.filter((t) => t.severity === 'urgent').length
  const warnings = tips.filter((t) => t.severity === 'warning').length

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-secondary">AI Recommendations</h1>
        <p className="mt-1 text-sm text-slate-500">
          Coaching tips and actionable insights generated by the SalesPulse AI engine.
        </p>
      </div>

      {/* KPI Row */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard title="Total Insights"   value={tips.length}    icon={BrainCircuit} helper="Active coaching queue" />
        <StatCard title="Urgent Actions"   value={urgent}         icon={Clock}        helper="Require action today" />
        <StatCard title="Warnings"         value={warnings}       icon={TrendingUp}   helper="Review this week" />
        <StatCard title="Opportunities"    value={tips.filter((t) => t.severity === 'opportunity').length} icon={CheckCircle} helper="Quick wins available" />
      </div>

      {/* Recommendation Cards */}
      <div className="space-y-4">
        {tips.map((tip) => {
          const s = SEVERITY_STYLES[tip.severity]
          return (
            <div
              key={tip.id}
              className={`rounded-xl border border-border border-l-4 ${s.border} bg-white p-5 shadow-sm`}
            >
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary text-xs font-bold text-white">
                    {tip.repInitials}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-secondary">{tip.rep}</p>
                    <p className="text-xs text-slate-500">{tip.created}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge tone={s.badge}>{s.label}</Badge>
                  <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${s.bg} ${s.text}`}>
                    {tip.metric}
                  </span>
                </div>
              </div>

              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">Issue Detected</p>
                  <p className="text-sm text-secondary">{tip.issue}</p>
                </div>
                <div className="rounded-lg bg-slate-50 border border-border p-3">
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">Recommended Action</p>
                  <p className="text-sm text-secondary">{tip.action}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500">
                    <span className="font-semibold text-secondary">Expected Impact: </span>
                    {tip.impact}
                  </p>
                </div>
              </div>
            </div>
          )
        })}

        {tips.length === 0 && (
          <Card>
            <div className="flex flex-col items-center py-12 text-center">
              <CheckCircle className="h-10 w-10 text-emerald-500 mb-3" />
              <p className="text-sm font-semibold text-secondary">All caught up!</p>
              <p className="text-xs text-slate-500 mt-1">No active recommendations for you right now.</p>
            </div>
          </Card>
        )}
      </div>
    </div>
  )
}
