-- View: vw_product_performance
-- Purpose: Analyze product line revenue performance, order volume, average ticket size, and active buyer count
-- Business metric: Product performance, revenue per product, order frequency, active buyer breadth
-- Updated: Automatically with each query (view recalculates fresh against base tables)
-- Used by: Product Management Dashboard, Merchandising, Pricing & Inventory Teams
-- 
-- Columns:
--   product_id       : Unique product primary key
--   product_name     : Name of the product module
--   category         : Product category classification
--   total_orders     : Count of distinct orders containing this product
--   total_units_sold : Total sum of units purchased
--   total_revenue    : Gross revenue generated by product
--   avg_unit_price   : Average unit selling price
--   unique_buyers    : Count of distinct active purchasing customers

CREATE VIEW IF NOT EXISTS vw_product_performance AS
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    SUM(oi.quantity) AS total_units_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue,
    ROUND(AVG(oi.unit_price), 2) AS avg_unit_price,
    COUNT(DISTINCT o.customer_id) AS unique_buyers
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_date >= date('now', '-90 days')
GROUP BY p.product_id, p.product_name, p.category;
