export const USER_ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  REPRESENTATIVE: 'REPRESENTATIVE',
};

export const DEAL_STAGES = {
  PROSPECT: 'PROSPECT',
  QUALIFICATION: 'QUALIFICATION',
  PROPOSAL: 'PROPOSAL',
  NEGOTIATION: 'NEGOTIATION',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
};

export const ACTIVITY_TYPES = {
  CALL: 'CALL',
  MEETING: 'MEETING',
  TASK: 'TASK',
  NOTE: 'NOTE',
  EMAIL: 'EMAIL',
};

export const SENTIMENTS = {
  POSITIVE: 'POSITIVE',
  NEUTRAL: 'NEUTRAL',
  NEGATIVE: 'NEGATIVE',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
